<?php
/**
 * This source file is subject to the (Open Source Initiative) BSD license
 * that is bundled with this package in the LICENSE file. It is also available
 * through the world-wide-web at this URL: http://www.webdawe.com.au/license.html
 * If you did not receive a copy of the license and are unable to obtain it through
 * the world-wide-web, please send an email to info@webdawe.com.au immediately.
 * Copyright (c) 2013-2017 Webdawe. (http://www.webdawe.com.au). All rights reserved.
 */
?>
<?php $fieldName = $this->getFieldsName();?>
<?php $fieldTitle = $this->getFieldsTitle();?>
<?php $fieldOptions = $this->getFieldsOptions();?>
<?php $fieldClass = $this->getFieldsClass();?>
<div class="input-box">
	<select id="<?php echo $fieldName?>" name="<?php echo $fieldName?>" title="<?php echo $fieldTitle ?>" class="<?php echo $fieldClass?>">
		<option value=""><?php echo $this->__('Any'); ?></option>
	<?php foreach ($fieldOptions as $value => $title):?>
		<option value="<?php echo $value;?>"<?php if ($this->getRequest()->getParam($fieldName) ==  $value): ?> selected="selected"<?php endif; ?>><?php echo $title; ?></option>
	<?php endforeach;?>
	</select>
</div>