<?php
/**
 * This source file is subject to the (Open Source Initiative) BSD license
 * that is bundled with this package in the LICENSE file. It is also available
 * through the world-wide-web at this URL: http://www.webdawe.com.au/license.html
 * If you did not receive a copy of the license and are unable to obtain it through
 * the world-wide-web, please send an email to info@webdawe.com.au immediately.
 * Copyright (c) 2013-2017 Webdawe. (http://www.webdawe.com.au). All rights reserved.
 */
?>
<form id="webdawe-salesreports-search-form" action="<?php echo $this->getSearchUrl()?>" method="POST">
    <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>" />
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->helper('webdawe_salesreports')->__('Search');?></h4>
        </div>
        <div class="fieldset">
        <table cellspacing="2" cellpadding="2" class="form-list">
            <tbody>
                <tr>
                    <td  style="width:65px;"><label for=""><?php echo $this->helper('webdawe_salesreports')->__('Product ID');?></label></td>
                    <td style="width:50px;">
                        <input id="_product_id" name="product_id" class="input-text validate-no-html-tags validate-alphanum-with-spaces" type="text" value="<?php echo $this->getRequest()->getParam('product_id');?>">
                    </td>


                    <td style="width:30px;padding-left:10px;"><em><strong><?php echo $this->helper('webdawe_salesreports')->__('or');?></strong></em></td>

                    <td style="width:50px;"><label for=""><?php echo $this->helper('webdawe_salesreports')->__('SKU');?></label></td>
                    <td style="width:50px;">
                        <input id="_sku" name="sku" class="input-text validate-no-html-tags validate-alphanum-with-spaces" type="text"  value="<?php echo $this->getRequest()->getParam('sku');?>">
                    </td>
                    <td  style="width:50px;padding-left:10px;"> <div class="input-wrapper input-submit">
                            <button class="button" type="submit"><?php echo $this->helper('webdawe_salesreports')->__('Go');?></button>
                        </div></td>
                </tr>
                <tr>
                    <td><?php echo $this->helper('webdawe_salesreports')->__('Store');?></td>
                    <td><?php echo $this->getStoreDropdown();?></td>
                    <td style="width:30px;padding-left:10px;">&nbsp;</td>
                    <td><?php echo $this->helper('webdawe_salesreports')->__('Month');?></td>
                    <td><?php echo $this->getMonthDropdown();?> <?php echo $this->getYearDropdown();?></td>
                </tr>

            </tbody>
        </table>
    </div>
</form>
