<div>
    <canvas id="canvas" height="450" width="600"></canvas>
</div>
<script>
    var randomScalingFactor = function(){ return Math.round(Math.random()*100)};


    jQuery(document).ready(
        function($)
        {
            var qtys = [];
            var totals = [];
            var labelsData = [];

            $('td.webdawe-salesreport-qty').each(
                function(index)
                {
                    qtys.push($(this).text());
                }
            );
            $('td.webdawe-salesreport-total').each(
                function(index)
                {
                    totals.push($(this).text());
                }
            );

            $('td.webdawe-salesreport-date').each(
                function(index)
                {
                    labelsData.push($(this).text());
                }
            );

            var lineChartData = {
                labels : labelsData,
                datasets : [
                    {
                        label: "Qty",
                        fillColor : "rgba(220,220,220,0.2)",
                        strokeColor : "rgba(220,220,220,1)",
                        pointColor : "rgba(220,220,220,1)",
                        pointStrokeColor : "#fff",
                        pointHighlightFill : "#fff",
                        pointHighlightStroke : "rgba(220,220,220,1)",
                        data : qtys
                    },
                    {
                        label: "Totals",
                        fillColor : "rgba(151,187,205,0.2)",
                        strokeColor : "rgba(151,187,205,1)",
                        pointColor : "rgba(151,187,205,1)",
                        pointStrokeColor : "#fff",
                        pointHighlightFill : "#fff",
                        pointHighlightStroke : "rgba(151,187,205,1)",
                        data : totals
                    }
                ]

            }

            var ctx = document.getElementById("canvas").getContext("2d");
            window.myLine = new Chart(ctx).Line(lineChartData, {
                responsive: true
            });

        }

    );
</script>