<?php
/**
 * This source file is subject to the (Open Source Initiative) BSD license
 * that is bundled with this package in the LICENSE file. It is also available
 * through the world-wide-web at this URL: http://www.webdawe.com.au/license.html
 * If you did not receive a copy of the license and are unable to obtain it through
 * the world-wide-web, please send an email to info@webdawe.com.au immediately.
 * Copyright (c) 2013-2017 Webdawe. (http://www.webdawe.com.au). All rights reserved.
 */
?>
<div class="webdawe-admin-daily">
<h1>Daily Report</h1>
<?php echo $this->getChildhtml('adminhtml_product_daily_form');?>
<?php echo $this->getChildhtml('adminhtml_product_daily_result');?>
</div>

